spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    # Mysql Settings
    url: jdbc:mysql://3.36.50.141:3306/tedbearDB?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: ${MYSQL_ROOT_PASSWORD}
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: none
      use-new-id-generator-mappings: false
    properties:
      hibernate:
        format_sql: true

  profiles:
    include: google, kakao, naver
  security:
    oauth2:
      client:
        registration:
          google:
            client-name: google
            provider: google
            client-id: ${google-client-id}
            client-secret: ${google-client-secret}
            scope:
              - profile
              - email
          kakao:
            client-name: kakao
            client-id: ${KAKAO_CLIENT_ID}
            redirect-uri: "{baseUrl}/oauth2/callback/{registrationId}"
            authorization-grant-type: authorization_code
            scope:
              - account_email
              - profile_nickname
            client-authentication-method: POST
          naver:
            client-name: naver
            client-id: ${naver-client-id}
            client-secret: ${naver-client-id}
            redirect-uri: "{baseUrl}/oauth2/callback/{registrationId}"
            authorization-grant-type: authorization_code
            scope:
              - email
              - name
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            user-info-uri: https://kapi.kakao.com/v2/user/me
            token-uri: https://kauth.kakao.com/oauth/token
            user-name-attribute: id
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            user-info-uri: https://openapi.naver.com/v1/nid/me
            token-uri: https://nid.naver.com/oauth2.0/token
            user-name-attribute: response

app:
  auth:
    token-secret: ${SECRET_KEY}


logging:
  level:
    org:
      hibernate:
        SQL: info
        type:
          descriptor:
            sql:
              BasicBinder: off
    com.ssafy.tedbear: debug

notification:
  mattermost:
    enabled: true # mmSender를 사용할 지 여부, false면 알림이 오지 않는다
    webhook-url: "https://meeting.ssafy.com/hooks/ucu18675zbncmm6nn1sj95if9c"
    color: "#000000"
    author-icon: "mattermost alert"
#    pretext: "에러에러"

#    author-name: "박일규"
#    channel: # 기본 설정한 채널이 아닌 다른 채널로 보내고 싶을 때 기입한다
#    footer: # attachment에 하단에 나올 부분. default=현재 시간

default-value:
  score: 30000